#include <stdlib.h>

#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#include "keymap.h"
#endif

enum custom_keycodes {
    DISCORD = SAFE_RANGE,
    YOUTUBE,
    IMEON,
    IMEOFF,
};

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* Keymap 0: Basic layer
     *
     * ,---------+-----------+---------+---------+---------+---------.
     * | Keymap1 | Backspace |    0    |    7    |    8    |    9    |
     * |---------+-----------+---------+---------+---------+---------|
     * |  Enter  |     ↑    |  Space  |    4    |    5    |    6    |
     * |---------+-----------+---------+---------+---------+---------|
     * |   ←    |     ↓    |    →    |    1    |    2    |    3    |
     * `---------+-----------+---------+---------+---------+---------'
     *
     */
    [0] = LAYOUT(TO(1), KC_BSPC, KC_0, KC_7, KC_8, KC_9,    //
                 KC_PENT, KC_UP, KC_SPC, KC_4, KC_5, KC_6,  //
                 KC_LEFT, KC_DOWN, KC_RGHT, KC_1, KC_2, KC_3),

    /* Keymap 1: Function layer
     *
     * ,------------+--------------+-------------+-------+-------+-------.
     * |  Keymap0   | Toggle Light |   Youtube   |  N/A  |  N/A  |  N/A  |
     * |------------+--------------+-------------+-------+-------+-------|
     * | Left Click |   Mouse Up   | Right Click |  N/A  |  N/A  |  N/A  |
     * |------------+--------------+-------------+-------+-------+-------|
     * | Mouse Left |  Mouse Down  | Mouse Right |  N/A  |  N/A  |  N/A  |
     * `------------+--------------+-------------+-------+-------+-------'
     *
     */
    [1] = LAYOUT(TO(0), RGB_TOG, YOUTUBE, KC_NO, KC_NO, KC_NO,    //
                 KC_BTN1, KC_MS_U, KC_BTN2, KC_NO, KC_NO, KC_NO,  //
                 KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_NO)};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif  // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case DISCORD:
            if (record->event.pressed) {
                register_code(KC_WSCH);
                wait_ms(100);
                SEND_STRING("discord.app");
                wait_ms(100);
                register_code(KC_ENT);
            } else {
                unregister_code(KC_WSCH);
                unregister_code(KC_ENT);
            }
            return false;
        case YOUTUBE:
            if (record->event.pressed) {
                // open spotlight
                register_code(KC_WSCH);
                wait_ms(100);

                // ime off
                register_code(KC_INT4);
                register_code(KC_LNG2);
                wait_ms(100);

                // open youtube
                SEND_STRING("https://www.youtube.com/watch?v=dQw4w9WgXcQ");
                wait_ms(5000);
                register_code(KC_DOWN);
                register_code(KC_DOWN);
                register_code(KC_ENT);
            } else {
                unregister_code(KC_WSCH);
                unregister_code(KC_INT4);
                unregister_code(KC_LNG2);
                unregister_code(KC_DOWN);
                unregister_code(KC_ENT);
            }
            return false;
        case IMEON:
            if (record->event.pressed) {
                register_code(KC_INT4);
                register_code(KC_LNG2);
            } else {
                unregister_code(KC_INT4);
                unregister_code(KC_LNG2);
            }
            return false;
        case IMEOFF:
            if (record->event.pressed) {
                register_code(KC_INT5);
                register_code(KC_LNG1);
            } else {
                unregister_code(KC_INT5);
                unregister_code(KC_LNG1);
            }
            return false;
        default:
            break;
    }
    return true;
}

#ifdef RGBLIGHT_ENABLE
void keyboard_post_init_user(void) {
    rgblight_mode(RGBLIGHT_MODE_STATIC_LIGHT);
    rgblight_set_speed(255);
}

bool rgb_matrix_indicators_user(void) {
    if (rand() % 2) {
        uint8_t h = rand() % 256;
        uint8_t s = 255;
        uint8_t v = 255;
        rgblight_sethsv_noeeprom(h, s, v);
        return false;
    } else {
        rgblight_sethsv_noeeprom(0, 0, 0);
        return true;
    }
}
#else
#endif  // RGB_MATRIX_ENABLE